### PR TITLE
Update application to TRIQS 3.2

### PR DESCRIPTION
**Pull request by Wentzell**

### CODE REVIEW

**Comment by krivenko** [comment]
It is a bit of a shame, but I already prepared a ported version of SOM, see the `triqs3.2` branch. The only reason why I haven't merged it into `master` yet is this issue: https://github.com/TRIQS/triqs/issues/914

**Comment by Wentzell** [comment]
Thats a bit unfortunate, I overlooked this fact. I addressed the issue you mentioned.

**Comment by krivenko** [comment]
Thank you for fixing the plotting issue! I will still have to fix some of SOM's benchmarks relying on the `Function` descriptor though.

**Comment by Wentzell** [comment]
In those cases I suggest using something like
```
for l in Gl.mesh: G[l] = f(l.index)
```

**Comment by krivenko** [comment]
I have merged `triqs3.2` into `master`, which means that porting is done and this PR can be closed.

**Pull request closed without merging**
